spring.datasource.url=jdbc:postgresql://localhost:5432/programacion_distribuida
spring.datasource.username=postgres
spring.datasource.password=Jwqnlfo?12
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/unnoba
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=unnoba
keycloak.client-id=pdyc
keycloak.client-secret=X6fHEZBaj5jVvFpv6rE0pSs2YcKqZeEz
